defaults: &dockerenvironment

version: 2.1

orbs:
  snyk: snyk/snyk@0.0.11

jobs:
  run_tests:
    <<: *dockerenvironment
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            sudo npm i -g
      - run:
          name: Run Unit Tests
          command: |
            ./node_modules/mocha/bin/mocha test/ --reporter mochawesome --reporter-options reportDir=test-results, reportFilename=test-results
  vulnerability_scan:
    <<: *dockerenvironment
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            sudo npm i -g
      - snyk/scan
workflows:
  build_test:
    jobs:
      - run_tests
      - vulnerability_scan
